n1=int(input('digite um numero ate 9999: '))
n1=str(n1)
print('analisando numero {}'.format(n1))
print('Unidade: {}'.format(n1[3]))
print('Dezena: {}'.format(n1[2]))
print('Centena: {}'.format(n1[1]))
print('Milhar: {}'.format(n1[0]))