A=input('digite algo:')
print ('a primitiva de a é ',type(A))
print('só tem espacos?',A.isspace())
print('é só numero?',A.isnumeric())
print('é alfabetico?',A.isalpha())
print('é alfanumérico?',A.isalnum())
print('é todo maiusculo?',A.isupper())
print('é todo minusculo?',A.islower())
print('é capitalizado?',A.istitle())